# Generated by Django 4.0.5 on 2022-07-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
